LAB_DESCRIPTION="SIRS project"

# images 

webserver[image]="xtrm0/quagga"
customerserver[image]="xtrm0/quagga"
switchcloudrv[image]="xtrm0/quagga"
routercloud[image]="xtrm0/quagga"
switchinternet[image]="xtrm0/quagga"
somepc[image]="xtrm0/quagga"
ana[image]="xtrm0/quagga"
bento[image]="xtrm0/quagga"
router1[image]="xtrm0/quagga"
packetfilter[image]="xtrm0/quagga"
router2[image]="xtrm0/quagga"
switch1[image]="xtrm0/quagga"
switch2[image]="xtrm0/quagga"
switch3[image]="xtrm0/quagga"
switch4[image]="xtrm0/quagga"
devserver1[image]="xtrm0/quagga"
pc1[image]="xtrm0/quagga"
ids[image]="redvector/snort"
fileserver[image]="xtrm0/quagga"
attackserver1[image]="xtrm0/quagga"
gpuserver1[image]="xtrm0/quagga"



# connections

customerserver[0]="A"
switchcloudrv[0]="A"

webserver[0]="B"
switchcloudrv[1]="B"

routercloud[0]="C"
switchcloudrv[2]="C"

routercloud[1]="D"
switchinternet[0]="D"

switchinternet[1]="E"
somepc[0]="E"

switchinternet[3]="S"
ana[0]="S"

switchinternet[4]="T"
bento[0]="T"

switchinternet[2]="F"
router1[1]="F"

router1[0]="G"
packetfilter[0]="G"

packetfilter[1]="H"
router2[0]="H"

router2[1]="I"
switch1[0]="I"

switch1[1]="J"
devserver1[0]="J"

router2[2]="M"
switch2[0]="M"

switch2[1]="N"
pc1[0]="N"

switch2[2]="O"
ids[0]="O"

switch2[3]="P"
fileserver[0]="P"

router2[3]="Q"
switch3[0]="Q"

switch3[1]="R"
attackserver1[0]="R"

router2[4]="U"
switch4[0]="U"

switch4[1]="V"
gpuserver1[0]="V"

